language: vim
sudo: required

branches:
  only:
    - master

install:
  - travis_retry sudo add-apt-repository -y ppa:pi-rho/dev
  # # Not for Precise.. :/
  # # - travis_retry sudo add-apt-repository -y ppa:pkg-vim/vim-daily
  - travis_retry sudo apt-get update

  - travis_retry sudo apt-get install -y tmux
  # - travis_retry hg clone https://vim.googlecode.com/hg vim
  # - ( cd vim && sudo make install )

before_script:
  - tmux -V
  - vim --version

script:
  - make travis
